[project]
name = 'STXMint'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.xusd-token]
path = 'contracts/xusd-token.clar'
clarity_version = 3
epoch = 3.1

[contracts.STXMint]
path = 'contracts/STXMint.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['xusd-token']

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
